
apiVersion: v1
kind: Service
metadata:
  name: {{ include "token.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "token.fullname" . }}
  ports:
   - name: "http"
     port: {{ .Values.service.port }}
     targetPort: "api-http"
