apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: {{ .Values.namespace }}

spec:
# Temporarily use Redis for pub/sub while waiting for https://github.com/dapr/components-contrib/issues/1372 to be released in 1.6.
  type: pubsub.redis
#  type: pubsub.rabbitmq
  version: v1
  metadata:
  #- name: host
  #  value: "amqp://rabbitmq:5672"
  #- name: durable
  #  value: "false"
  #- name: deletedWhenUnused
  #  value: "false"
  #- name: autoAck
  #  value: "false"
  #- name: reconnectWait
  #  value: "0"
  #- name: concurrency
  #  value: parallel
  
  # - name: redisHost
  #   value: redis:6379
  # - name: redisPassword
  #   secretKeyRef:
  #     name: insurance-secrets
  #     key: RedisPassword

  - name: redisHost
    value: 10.104.142.36:30137
    # value: localhost:6379
  - name: redisPassword
    value: "jEr4Qk56HtpS4k1G75"
auth:
  secretStore: insurance-secretstore

