apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: {{ .Values.namespace }}

spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    secretKeyRef:
      name: insurance-secrets
      key: RedisPassword
  - name: actorStateStore
    value: "true"
  - name: keyPrefix
    value: name
auth:
  secretStore: insurance-secretstore
