apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: {{ .Values.namespace }}

spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    secretKeyRef:
      name: insurance-secrets
      key: RedisPassword
  - name: actorStateStore
    value: "true"
  - name: keyPrefix
    value: name
auth:
  secretStore: insurance-secretstore
  
#   - name: redisHost
#     value: 10.104.142.36:30137
#   - name: redisPassword
#     value: jEr4Qk56HtpS4k1G75
#     # secretKeyRef:
#     #   name: insurance-secrets
#     #   key: RedisPassword
#   - name: actorStateStore
#     value: "true"
#   - name: keyPrefix
#     value: name
# # auth:
# #   secretStore: insurance-secretstore
