namespace: dev
hostName: localhost

config:
  app_port: 8080

service:
  type: ClusterIP
  port: 80

cpgweb:
  image:
    repository: dockerhost.charisma.tech/cpg-web
    tag: latest
  # image_db:
  #   repository: localhost:5001/insurance-share-api-dbup
  #   tag: latest  
  replicas: 1
  min_ready_seconds: 60
  block_config: "block-config"
  # sql:
  #   server: sqlserver.dev.svc.cluster.local
  #   port: 1433
  #   database: Share
  #   user_id: sa
  #   password: Admin@123
  idp:
    uri: dev-idp  
  otel:
    uri: dev-otel 