apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "share.fullname" . }}-dbup
  namespace: {{ .Values.namespace }}
  
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded

spec:
  backoffLimit: 5
  template:
    metadata:
      labels:
        app: {{ include "share.fullname" . }}-dbup
    spec:
      containers:
      - name: {{ include "share.fullname" . }}-dbup
        image:  {{ list .Values.share.image_db.repository ":" .Values.share.image_db.tag | join "" }} 
        imagePullPolicy: Always
        env:
        - name: SHARE_SQL_CONNECTION
          valueFrom:
            configMapKeyRef:
              name: {{ include "share.fullname" . }}-env
              key: SHARE_SQL_CONNECTION 
      restartPolicy: Never     
