kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "share.fullname" . }}-env
  namespace: {{ .Values.namespace }}
  labels:
    app: insurance
    service: {{ include "share.fullname" . }}
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
  ASPNETCORE_URLS: {{ list "http://+:" .Values.config.app_port | join "" |  quote }}
  # SHARE_SQL_CONNECTION: {{ list "Server=" .Values.share.sql.server "," .Values.share.sql.port ";Database=" .Values.share.sql.database ";User ID=" .Values.share.sql.user_id ";Password=" .Values.share.sql.password ";TrustServerCertificate=true;" | join "" |  quote }} 
  # "Server=sqlserver.dev.svc.cluster.local,1433;Database=master;User ID=sa;Password=Admin@123;TrustServerCertificate=true;"
  # "Server=localhost;Database=Share;User ID=sa;Password=Admin@123;TrustServerCertificate=true;"

