namespace: dev
hostName: localhost

config:
  app_port: 8080

service:
  type: ClusterIP
  port: 80

gateway:
  image:
    repository: dockerhost.charisma.tech/insurance-core-gateway
    tag: latest
  replicas: 1
  min_ready_seconds: 60
