namespace: dev
hostName: localhost

config:
  app_port: 80

service:
  type: LoadBalancer
  port: 8085

gateway:
  image:
    repository: dockerhost.charisma.tech/insurance-core-gateway
    tag: latest
  replicas: 1
  min_ready_seconds: 60
