apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  minReadySeconds: {{ .Values.otel.min_ready_seconds }}
  replicas: {{ .Values.otel.replicas }}
  selector:
    matchLabels:
      app: {{ include "otel.fullname" . }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ include "otel.fullname" . }}
    spec:
      containers:
      - name: {{ include "otel.fullname" . }}
        image:  {{ list .Values.otel.image.repository ":" .Values.otel.image.tag | join "" }} 
        imagePullPolicy: Always
        ports:
        - name: "api-http"
          containerPort: {{ .Values.config.app_port }}
          protocol: TCP
        - name: "otel-http"
          containerPort: {{ .Values.config.otel_port }}
          protocol: TCP  
        envFrom:
        - configMapRef:
           name: {{ include "otel.fullname" . }}-env
