namespace: dev
hostName: localhost

config:
  app_port: 8080

service:
  type: ClusterIP
  port: 80

share:
  image:
    repository: dockerhost.charisma.tech/insurance-share-api-main
    tag: latest
  image_db:
    repository: dockerhost.charisma.tech/insurance-share-api-dbup
    tag: latest   
  replicas: 1
  min_ready_seconds: 60
  block_config: "block-config"
