namespace: dev
hostName: localhost

config:
  app_port: 8080

service:
  type: ClusterIP
  port: 80

idp:
  image:
    repository: dockerhost.charisma.tech/insurance-idp
    tag: latest
  replicas: 1
  min_ready_seconds: 60
  block_config: "block-config"
