# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ingress-single
# spec:
#   ingressClassName: nginx
#   defaultBackend:
#     service:
#         name: dev-share
#         port: 
#             number: 80



# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{ .Release.Name }}-{{ .Chart.Name }}-ingress
#   namespace: {{ .Values.namespace }}
# spec:
#   ingressClassName: nginx
#   rules:
# {{- range .Values.ingress.hosts }}
#   - host: {{ $.Release.Name }}.{{ .host.domain }}
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: {{ $.Release.Name}}-{{ .host.chart }}
#             port: 
#               number: 80
# {{- end }}


