namespace: dev
hostName: localhost

config:
  app_port: 8080

service:
  type: ClusterIP
  port: 80

token:
  image:
    repository: dockerhost.charisma.tech/insurance-token-fanavaran-client
    tag: latest
  replicas: 1
  min_ready_seconds: 60
  block_config: "block-config"

# idp:
#     uri: {{ .Release.Name }}-idp