kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "gateway.fullname" . }}-env
  namespace: {{ .Values.namespace }}
  labels:
    app: insurance
    service: {{ include "gateway.fullname" . }}
data:
  ASPNETCORE_URLS: {{ list "http://+:" .Values.config.app_port | join "" |  quote }}
  